### PR TITLE
Fix lib_root for upcoming change to bazel.

### PR DESCRIPTION
**Pull request by DrMarcII**
See bazelbuild/bazel#1681 and bazelbuild/rules_webtesting#94.

This change should be forward and backwards compatible.

### CODE REVIEW

**Comment by natebosch** [comment]
How can I repro? Do I need to be on a specific version of bazel?

**Comment by DrMarcII** [comment]
You need to build bazel from: https://github.com/kchodorow/bazel/tree/execroot (`bazel build //src:bazel`). You can check out rules_webtesting from: https://github.com/kchodorow/rules_webtesting, then run `bazel test //dart/...`.

**Comment by DrMarcII** [comment]
I have updated this PR. Before the rules were not always compatible with bazel 0.4.4 (not sure why). Now they are. Unfortunately, I don't have an earlier version of bazel around, so I am not sure if this change works before 0.4.4.

**Comment by DrMarcII** [comment]
Hmm, not sure if this solves the entire problem. In Bazel 0.4.4, with this change, I am getting errors in some libraries when I enable ddc.

**Comment by DrMarcII** [comment]
After further examination this change fixes package imports when running tests with Bazel 0.4.4+, but breaks package imports in DDC builds in Bazel 0.4.4+.

You can recreate the original issue I was trying to fix by checking out https://github.com/DrMarcII/webdriver.dart/tree/pub_deps and running `bazel test //test:async_test`.

You can recreate the DDC build issue by changing the http_archive rule in WORKSPACE for io_bazel_rules_dart to:
`
http_archive(
    name = "io_bazel_rules_dart",
    strip_prefix = "rules_dart-8e7a3dd6b5ac0bbd451ccafffcc02eac5575615b",
    urls = ["https://github.com/DrMarcII/rules_dart/archive/8e7a3dd6b5ac0bbd451ccafffcc02eac5575615b.tar.gz"],
)
`
and running `bazel build :com_github_google_webdriver_dart`.

At this point I am lost as to where I should be looking for the problem, so any advice would be helpful.

**Comment by natebosch** [comment]
Dug in to a similar looking issue - I think a good chunk of the weird stuff we're doing is because of the way `pub_repository()` works, and how we're using it from `vendor/`. We put a level of indirection between the `dart_library` and the `srcs` which doesn't work well. I'm not sure if this is necessary in the long term - there are legitimate use cases for pulling in another target's dart files into `srcs`

I think that there is a very good chance the `layout_action` can be skipped entirely, and that we'll be able to remove a lot of the hardcoding around `external` and `vendor` - but there is a lot that would need to get overhauled all at once.

**Comment by natebosch** [comment]
Can you try syncing past https://github.com/dart-lang/rules_dart/pull/92 and see how that impacts things?

If you are using the technique we had with vendor/ and pub_repository you'll need to tweak some things - overall though I *think* it makes things a bit simpler and could help us narrow in on the problem.

**Comment by DrMarcII** [comment]
I synced and rebased and am getting the same behavior with Bazel 0.4.4 as before:

Without this change compiles works, but tests can't find imported files.

With this change compiles can't find imported files, but tests work.

I will create a simpler example project that we can use to iterate on.

**Comment by DrMarcII** [comment]
I have created a simple example project that demonstrates the issue:
https://github.com/DrMarcII/rules_dart_example

You can check this out, and run bazel test --keep_going ...

You can switch between using this PR and not by (un)commenting the appropriate lines near the top of the WORKSPACE file.

If you are using this PR, you should see tests pass but get a DDC error.
If you don't use this PR, you should see the compile succeed, but get an error during tests.

**Comment by natebosch** [comment]
I was *really* hoping that https://github.com/dart-lang/rules_dart/pull/95 would fix this, but it doesn't :(

I found a fix on top of that that makes the smaller repro work: https://github.com/dart-lang/rules_dart/pull/101 - could you try this in the webdriver repo?

I don't have any mental model that would explain why we need to do this in such narrow conditions so it feel extremely hacky. If it was just the check for runfiles this might make sense - runfiles has a different layout than execroot - but the fact that it's also different depending on wether the test is in the top-level package is extra scary.

**Comment by DrMarcII** [comment]
Sorry about the delay. I tried #101, and am still getting an error when running tests:

Unhandled exception:
Could not import "package:path/path.dart" from "file:///usr/local/google/home/fisherii/.cache/bazel/_bazel_fisherii/c7da029a34d9c11bbaf4adefc53f76bd/execroot/webdriver.dart/bazel-out/local-fastbuild/bin/test/window_test_io_chromium-native.runfiles/com_github_google_webdriver_dart/test/io_test_util.dart": FileSystemException: Cannot open file, path = '/usr/local/google/home/fisherii/.cache/bazel/_bazel_fisherii/c7da029a34d9c11bbaf4adefc53f76bd/execroot/webdriver.dart/bazel-out/local-fastbuild/bin/test/window_test_io_chromium-native.runfiles/com_github_google_webdriver_dart/org_dartlang_pub_path/_merged_lib/path.dart' (OS Error: No such file or directory, errno = 2)

**Pull request closed without merging**
