### PR TITLE
Eliminate unnecessary selects on host_cpu

### PR DESCRIPTION
**Pull request by cbracken**
Restrict select() calls to cases where the underlying targets are
platform-specific.

### CODE REVIEW

**Comment by natebosch** [comment]
Will any of these selects become necessary when we add windows targets?

**Comment by nshahan** [comment]
Yes, I'm pretty sure at that point we will need to add different batch scripts (.bat files) for windows targets.

**Comment by cbracken** [comment]
None of *these* selects will be necessary, but it's very likely that *a* select will become necessary. My feeling is that the least bad solution when that time comes will be to use ``//conditions:default` for the Linux/macOS versions and call out Windows as the exception.

The motivation for this change is that the default toolchain on macOS [recently changed](https://github.com/bazelbuild/bazel/commit/900202fe4418490abca96afd7ebf2b92268be244) to `ios_x86_64`, so eliminating as many unnecessary selects on Darwin is not a bad idea.

**Comment by jakemac53** [comment]
What if we left the selects but just change them to only contain `//conditions:default`. That would make it easier to know where to go add windows things later?

**Comment by cbracken** [comment]
That works too, though it's a bit of a readability head-scratcher to see a `select` with only a default condition. I suspect that anyone working on these rules is (or should be) aware of how to add a `select` when needed.

**Comment by cbracken** [comment]
FWIW, `host_cpu` isn't a particularly good choice for selecting on target OS, it's just the least-bad solution available at present. There's a separate bug against Bazel to provide a better means of doing this, so long-term, I'd expect we move away from selecting on `host_cpu` either way.

**Comment by natebosch** [comment]
I'm happy with the changes as is. I suspect that when we look at adding windows support we'll have enough things to tackle that we'll want to start with fresh eyes and not assume that these choices still make sense.

**Pull request merged**
