### PR TITLE
Clean up more places hardcoding `vendor`

### PR DESCRIPTION
**Pull request by natebosch**
- `vendor/` doesn't exist, don't need to check for it
- Don't need to strip `vendor_` since it doesn't matter whether the
  path in the snapshot exactly matches the package name

### CODE REVIEW

**Comment by nshahan** [comment]
How are we keeping the dependencies used by our rules separate from the users dependencies?

**Comment by natebosch** [comment]
Our dependencies look like `@vendor_package_name`, user dependencies look like `@pub_package_name`

**Comment by nshahan** [comment]
OK cool are those the names of the directories when you look through the output of a bazel build?

**Comment by natebosch** [comment]
Yes, the directories have those prefixes in their names

**Pull request merged**
